services:
  database:
    image: mysql:8.0
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fifa-manager-database
    volumes:
      - ./apps/backend/database:/docker-entrypoint-initdb.d